### ISSUE TITLE
Docker run failed, no such file or directory

### ISSUE THREAD

**Issue by mendoanjoe** [ShaunLWM/action-release-debugapk#1]
Here my yml file
```yml
name: Build & Publish Debug APK
on:
 push:
  branches:
   - master
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@master
   - name: Publish Debug APK
     uses: ShaunLWM/action-release-debugapk@master
     env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      APP_FOLDER: pre-release
      RELEASE_TITLE: "New Build"
```

and here my error message
```console
Switched to a new branch 'master'
Branch 'master' set up to track remote branch 'master' from 'origin'.
Attaching release asset `./pre-release/build/outputs/apk/debug/app-debug.apk'...
Error uploading release asset: stat ./pre-release/build/outputs/apk/debug/app-debug.apk: no such file or directory
##[error]Docker run failed with exit code 1
```

**Comment by ShaunLWM** [comment]
I apologize for the late reply. I didn't receive any notification for this.
You'll need the official `actions/setup-java` to compile the APK before it can be uploaded.
I wasn't clear in the README and I apologise for that. I'll update the README for clarity.

Here's a sample of the full yml file.

```
name: Android CI

on:
 push:
  branches:
   - master
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Releasing using Hub
      uses: ShaunLWM/action-release-debugapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: app
       RELEASE_TITLE: New Build
```
